title: "CIS6200: Deep Learning at Scale"
description: "Graduate course on core architectures and training methods in contemporary deep learning"
baseurl: "/CIS6220"
url: ""

# Theme
theme: minima

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Navigation
header_pages:
  - index.md
  - schedule.md
  - resources.md
  - project.md

# Site settings
author:
  name: "Lyle Ungar"
  email: "ungar@cis.upenn.edu"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
